# Keystore configurations
# Update these with your real values before building release
KEY_ALIAS=faithtech-alias
KEY_PASSWORD=changeit
STORE_FILE=C\:\\Users\\acer\\Downloads\\FaithTech\\FaithTech\\faithtech.jks
STORE_PASSWORD=changeit
